{{- if .Values.secretprovider.enabled }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: adotoken
  namespace: {{ .Values.namespace }}
spec:
  provider: azure
  secretObjects:
    - data:
      - key: adotoken
        objectName: ADOTOKEN
      secretName: adotoken
      type: Opaque
  parameters:
    usePodIdentity: {{.Values.secretprovider.usePodIdentity | quote | default "false" }}
    useVMManagedIdentity: {{ .Values.secretprovider.useVMManagedIdentity | quote | default "true" }}
    userAssignedIdentityID: {{ .Values.secretprovider.userAssignedIdentityID | quote }}
    keyvaultName: {{ .Values.secretprovider.keyVaultName }}
    objects: |
       array:
         - |
           objectName: ADOTOKEN
           objectType: secret
           objectVersion: ""
    tenantId: {{ .Values.secretprovider.tenandId }}
{{- end }}
